/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_744BEF80".
 */
export type LexicalNodes_744BEF80 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_744BEF80>
  | SerializedAutoLinkNode<LexicalNodes_744BEF80, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_744BEF80, LexicalLinkFields>;

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    folders: Folder;
    'ai-tasks': AiTask;
    chapters: Chapter;
    comments: Comment;
    favorites: Favorite;
    'reading-progress': ReadingProgress;
    stories: Story;
    media: Media;
    categories: Category;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    folders: FoldersSelect<false> | FoldersSelect<true>;
    'ai-tasks': AiTasksSelect<false> | AiTasksSelect<true>;
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'reading-progress': ReadingProgressSelect<false> | ReadingProgressSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  _h_folders?: (number | null) | Folder;
  name: string;
  updatedAt: string;
  createdAt: string;
  _h_slugPath?: string | null;
  _h_titlePath?: string | null;
}
/**
 * INTERNAL ONLY. AI 输出仅为草稿（isDraftOutput 默认为 true），不能自动发布内容。不连接外部 API。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-tasks".
 */
export interface AiTask {
  id: number;
  taskType:
    'translation_assist' | 'metadata_generation' | 'comment_moderation' | 'seo_copy_draft' | 'performance_insight';
  status?: ('queued' | 'processing' | 'draft_complete' | 'approved' | 'rejected' | 'failed') | null;
  /**
   * The story or chapter this AI task is targeting.
   */
  target?:
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null);
  /**
   * Input parameters for the AI task.
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * AI output — DRAFT ONLY, cannot be used to publish content.
   */
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Name of the AI model used.
   */
  model?: string | null;
  /**
   * Version identifier for the prompt used.
   */
  promptVersion?: string | null;
  /**
   * Virtual / estimated cost — no real billing.
   */
  cost?: number | null;
  /**
   * Admin who approved the AI output.
   */
  approvedBy?: (number | null) | User;
  /**
   * Error message if the task failed.
   */
  error?: string | null;
  /**
   * AI output is draft only and cannot be used to auto-publish content.
   */
  isDraftOutput?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  titleAr: string;
  synopsisAr?: LexicalRichText<LexicalNodes_744BEF80> | null;
  titleZh?: string | null;
  synopsisZh?: LexicalRichText<LexicalNodes_744BEF80> | null;
  slug?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  authorName?: string | null;
  /**
   * e.g., فانتازيا, رعب, خيال علمي, رومانسي, تاريخي
   */
  genre?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Admin-only field for tracking total chapters
   */
  totalChapters?: number | null;
  contentStatus?: ('draft' | 'review' | 'approved' | 'published' | 'retired') | null;
  editorialStatus?:
    ('candidate' | 'briefed' | 'drafting' | 'qa' | 'human-review' | 'approved' | 'released' | 'retired') | null;
  rightsStatus?: ('unknown' | 'reviewing' | 'cleared' | 'restricted' | 'expired' | 'rejected') | null;
  riskLevel?: ('none' | 'low' | 'medium' | 'high') | null;
  riskNotes?: string | null;
  /**
   * Mark this story as demo data, not for production use
   */
  demoOnly?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  _h_folders?: (number | null) | Folder;
  caption?: LexicalRichText<LexicalNodes_744BEF80> | null;
  altAr?: string | null;
  mediaType?: ('cover' | 'audio' | 'video' | 'epub' | 'image') | null;
  rightsStatus?: ('unknown' | 'reviewing' | 'cleared' | 'restricted' | 'expired' | 'rejected') | null;
  sourceUrl?: string | null;
  /**
   * e.g., Unsplash, Pexels, Custom
   */
  sourceLabel?: string | null;
  /**
   * Mark this media as demo data, not for production use
   */
  demoOnly?: boolean | null;
  /**
   * Storage provider for this media file
   */
  provider?: ('local' | 'r2') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  titleAr: string;
  bodyAr?: LexicalRichText<LexicalNodes_744BEF80> | null;
  titleZh?: string | null;
  bodyZh?: LexicalRichText<LexicalNodes_744BEF80> | null;
  slug?: string | null;
  chapterNumber: number;
  story: number | Story;
  wordCount?: number | null;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Mark this chapter as demo data, not for production use
   */
  demoOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  body: LexicalRichText<LexicalNodes_744BEF80>;
  author: number | User;
  story?: (number | null) | Story;
  chapter?: (number | null) | Chapter;
  parent?: (number | null) | Comment;
  status?: ('pending' | 'approved' | 'rejected' | 'hidden') | null;
  /**
   * Reason for the moderation decision.
   */
  moderationReason?: string | null;
  /**
   * Admin-only field.
   */
  likeCount?: number | null;
  /**
   * Admin-only field.
   */
  aiRecommendation?: ('none' | 'approve' | 'reject' | 'flag_review') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  story: number | Story;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-progress".
 */
export interface ReadingProgress {
  id: number;
  user: number | User;
  story: number | Story;
  chapter?: (number | null) | Chapter;
  /**
   * Reading progress as a percentage (0–100)
   */
  progressPercentage?: number | null;
  lastReadAt?: string | null;
  completed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'ai-tasks';
        value: number | AiTask;
      } | null)
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'reading-progress';
        value: number | ReadingProgress;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  _h_folders?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  _h_slugPath?: T;
  _h_titlePath?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-tasks_select".
 */
export interface AiTasksSelect<T extends boolean = true> {
  taskType?: T;
  status?: T;
  target?: T;
  input?: T;
  output?: T;
  model?: T;
  promptVersion?: T;
  cost?: T;
  approvedBy?: T;
  error?: T;
  isDraftOutput?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  titleAr?: T;
  bodyAr?: T;
  titleZh?: T;
  bodyZh?: T;
  slug?: T;
  chapterNumber?: T;
  story?: T;
  wordCount?: T;
  status?: T;
  publishedAt?: T;
  demoOnly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  body?: T;
  author?: T;
  story?: T;
  chapter?: T;
  parent?: T;
  status?: T;
  moderationReason?: T;
  likeCount?: T;
  aiRecommendation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  story?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-progress_select".
 */
export interface ReadingProgressSelect<T extends boolean = true> {
  user?: T;
  story?: T;
  chapter?: T;
  progressPercentage?: T;
  lastReadAt?: T;
  completed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  titleAr?: T;
  synopsisAr?: T;
  titleZh?: T;
  synopsisZh?: T;
  slug?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  authorName?: T;
  genre?: T;
  coverImage?: T;
  totalChapters?: T;
  contentStatus?: T;
  editorialStatus?: T;
  rightsStatus?: T;
  riskLevel?: T;
  riskNotes?: T;
  demoOnly?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _h_folders?: T;
  caption?: T;
  altAr?: T;
  mediaType?: T;
  rightsStatus?: T;
  sourceUrl?: T;
  sourceLabel?: T;
  demoOnly?: T;
  provider?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stories';
            value: number | Story;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'stories';
            value: number | Story;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription: string;
  /**
   * ISO 639-1 language code
   */
  defaultLocale: string;
  defaultDirection: 'rtl' | 'ltr';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultLocale?: T;
  defaultDirection?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'folders'
      | 'ai-tasks'
      | 'chapters'
      | 'comments'
      | 'favorites'
      | 'reading-progress'
      | 'stories'
      | 'media'
      | 'categories'
      | 'users';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'folders'
          | 'ai-tasks'
          | 'chapters'
          | 'comments'
          | 'favorites'
          | 'reading-progress'
          | 'stories'
          | 'media'
          | 'categories'
          | 'users'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}