-- Phase 3A operator template. Replace password placeholders outside Git.
-- Run as a database administrator after reviewing the target database and schema.

CREATE ROLE kr1688_migrate LOGIN PASSWORD '<SET_OUTSIDE_GIT>';
CREATE ROLE kr1688_app LOGIN PASSWORD '<SET_OUTSIDE_GIT>';
CREATE ROLE kr1688_backup LOGIN PASSWORD '<SET_OUTSIDE_GIT>';

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

GRANT USAGE, CREATE ON SCHEMA public TO kr1688_migrate;
GRANT USAGE ON SCHEMA public TO kr1688_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kr1688_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO kr1688_app;
ALTER DEFAULT PRIVILEGES FOR ROLE kr1688_migrate IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kr1688_app;
ALTER DEFAULT PRIVILEGES FOR ROLE kr1688_migrate IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO kr1688_app;

GRANT CONNECT ON DATABASE <KR1688_DATABASE> TO kr1688_backup;
GRANT USAGE ON SCHEMA public TO kr1688_backup;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO kr1688_backup;
